services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami
    networks:
      - whoami_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${HOST_DOMAIN}`) && PathPrefix(`/${HOST_PREFIX}`)"
      # # Define the middleware
      - "traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/${HOST_PREFIX}"
      # # Attach the middleware that strips the prefix
      - "traefik.http.routers.whoami.middlewares=whoami-stripprefix"

networks:
  whoami_network:
    external: true
    # Only traefik could access