version: '3.8'

services:
  test_flask_api:
    image: river1440ce/test_flask_api
    container_name: test_flask_api
    networks:
      - test_flask_api_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_flask_api.rule=Host(`${TEST_FLASK_API_HOST}`)"

networks:
  test_flask_api_network:
    driver: bridge
    name: test_flask_api_network