services:
  test_flask_api:
    image: river1440ce/test_flask_api
    container_name: test_flask_api
    networks:
      - test_flask_api_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_flask_api.rule=Host(`${HOST_DOMAIN}`) && PathPrefix(`/${HOST_PREFIX}`)"
      # # Define the middleware
      - "traefik.http.middlewares.test_flask_api-stripprefix.stripprefix.prefixes=/${HOST_PREFIX}"
      # # Attach the middleware that strips the prefix
      - "traefik.http.routers.test_flask_api.middlewares=test_flask_api-stripprefix"

networks:
  test_flask_api_network:
    external: true